import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import ReduxProvider from "@/providers/ReduxProvider";
import { Locale } from "@/i18n.config";
import { Directions, Languages } from "@/constants/enum";
import SessionProvider from "@/providers/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/server/auth";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Pizza",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>;
}>) {
  const locale = (await params).locale;
  const session = await getServerSession(authOptions);

  return (
    <html
      lang={locale}
      dir={locale == Languages.ARABIC ? Directions.RTL : Directions.LTR}
    >
      <body className={roboto.className}>
        <SessionProvider session={session}>
          <ReduxProvider>{children}</ReduxProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
