import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Header from "@/components/header/page";
import Footer from "@/components/footer/Footer";
import ReduxProvider from "@/providers/ReduxProvider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Pizza",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={roboto.className}>
        <ReduxProvider>
          <div className="min-h-[100vh] flex flex-col">
            <Header />
            <div className="mt-5 flex-1">{children}</div>
            <Footer />
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
